- Makefile
- cmd/klepto.go
When dumping, we want to be able to specify
the kind of record to dump. A record type roughly
corresponds to one table. The detail is that
a record is not simply the rows from a table,
but also the rows from other tables that the table
has foreign key relationships with.
--number looks like a better description for the flag to specify number of rows.
A sample command would look like this:
klepto \
--from 'root:root@tcp(localhost:3306)/fromDB' \
--to 'root:root@tcp(localhost:3306)/toDB' \
--primary-record-type 'user' \
--number '10'
> Improve flag descriptions

- database/mysql/relresolver.go
- database/mysql/relresolver_test.go
Provide a way to explicitly set relationships in the
configuration file. Read the configurations and
store them in a convenient map that we will
use for future action.
> Read relationships from config

- database/mysql/relresolver_test.go
- example.toml
With this set, we can determine the primary_record_type (or table).
The user can also set the number of records that they want in the config.
> Add support for primary_record_type in the config

- database/database.go
- database/mysql/anonymiser.go
- database/mysql/dumper.go
- database/mysql/seeder.go
- database/mysql/seeder_test.go
- database/storage.go
Typically, during troubleshooting and testing, we want
the newest records
> By default, order records in descending order by primary key

- cmd/klepto.go
- cmd/steal.go
- database/database.go
- database/mysql/anonymiser.go
- database/mysql/dumper.go
- database/mysql/seeder.go
- database/mysql/seeder_test.go
- database/relresolver.go
- database/relresolver_test.go
- database/storage.go
We want to use only the primary record to generate
the query if the user specifies that in the configuration.
Otherwise, we want to get tables from the db and dump everything.
Next up, we dump related tables too.
> Dump configured record

- cmd/update.go
Fixes this error when you try to `./klepto update`
```
⨯ could not create the updater client error=to check for updates you must provide a github token
```
> Get GitHub token from options

- pkg/anonymiser/anonymiser_test.go
- pkg/dumper/text/dumper.go
- pkg/dumper/text/dumper_test.go
- pkg/reader/mysql/reader.go
- pkg/reader/postgres/pg_dump.go
- pkg/reader/reader.go
This PR changes `reader.Reader` to dump the database for the tables and not just a table at a time. This makes postgres structure a lot more usable.
> Get database structure not table structure

- cmd/steal.go
- pkg/dsn/dsn.go
- pkg/dumper/dumper.go
- pkg/dumper/mysql/mysql.go
- pkg/dumper/query/query.go
- pkg/dumper/query/writer.go
- pkg/dumper/query/writer_test.go
- pkg/reader/mysql/mysql.go
- pkg/reader/reader.go
We can do `klepto steal --from 'root:@tcp(localhost:3307)/fromDB' -c .klepto.toml --to 'os://stdout/'`
`os://stdout` without a trailing slash gives an error that the dsn is invalid. Will fix that in another PR.
> Parse dumper dsn, and output to os streams

- pkg/dumper/mysql/dumper.go
- pkg/reader/mysql/reader.go
- Minor: adds new line when dumping to stdout
- Fixes a bug with interface conversion when dumping into a target database
```
panic: interface conversion: interface {} is []uint8, not string
goroutine 25 [running]:
github.com/hellofresh/klepto/pkg/dumper/mysql.(*myDumper).insertIntoTable.func1(0xc420074480, 0xc4200f8d00, 0x5, 0x8, 0xc42001b0b0, 0xc42000e1d8)
/Users/jojoo/go/src/github.com/hellofresh/klepto/pkg/dumper/mysql/dumper.go:106 +0x61b
created by github.com/hellofresh/klepto/pkg/dumper/mysql.(*myDumper).insertIntoTable
/Users/jojoo/go/src/github.com/hellofresh/klepto/pkg/dumper/mysql/dumper.go:88 +0x4ce
```
> Improve mysql dumper

- README.md
- cmd/init.go
- cmd/steal.go
- docker-compose.yml
- features/mysql_test.go
- features/postgres_test.go
- fixtures/mysql_simple.sql
- fixtures/pg_simple.sql
- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
- pkg/config/config.go
- pkg/dumper/dumper.go
- pkg/dumper/generic/sql.go
- pkg/dumper/postgres/dumper.go
- pkg/dumper/query/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/mysql/reader.go
- pkg/reader/reader.go
This PR implements a new field `match`  which allows seamless dumping table based on the matching condition.
Here are some example of the matching conditions:
- `Match = "users.id IN (1, 2, 3)"`
- `Match = "users.id >= 500`
- `Match = "users.created_at BETWEEN '2018-01-01' AND now()`
The users -> orders sample could be mapped as follows:
```toml
[[Tables]]
Name = "users"
[Tables.Filter]
Match = "users.created_at BETWEEN '2017-01-01' AND now()"
[[Tables]]
Name = "orders"
[Tables.Filter]
Match = "users.created_at BETWEEN '2017-01-01' AND now()"
[[Tables.Relationships]]
ReferencedTable = "users"
ReferencedKey = "id"
ForeignKey = "user_id"
```
> Fix relationships 

- README.md
- cmd/init.go
- pkg/config/config.go
- pkg/dumper/generic/sql.go
This feature will allow users to dump the source database structure without importing data when the table has the following configuration:
```toml
[[Tables]]
Name = "logs"
IgnoreData = true
```
> Add IgnoreData config option

- README.md
- examples/user-orders.toml
- examples/user.toml
- fixtures/mysql_simple.sql
- fixtures/pg_simple.sql
- pkg/config/config.go
- pkg/dumper/generic/sql.go
- pkg/reader/generic/sql.go
- pkg/reader/reader.go
The current implementation does not allow filtering complex relationships, this PR add capabilities for the klepto users to proper filter table with relationships. Let's take this scenario:
I want to dump only the active `users` with their `orders` and it's `order_items`
And need to anonymise the email and firstName fields respectively
Given the klepto config
```toml
[[Tables]]
Name = "users"
[Tables.Anonymise]
email = "EmailAddress"
firstName = "FirstName"
[Tables.Filter]
Match = "users.active = TRUE"
[[Tables]]
Name = "orders"
PrimaryKey = "id"
[[Tables.Relationships]]
Table = "orders"
ForeignKey = "user_id"
ReferencedTable = "users"
ReferencedKey = "id"
[Tables.Filter]
Match = "users.active = TRUE"
[[Tables]]
Name = "order_items"
PrimaryKey = "id"
[[Tables.Relationships]]
Table = …
```
> Expose join capabilities api

- README.md
- examples/user-orders.toml
- pkg/config/config.go
- pkg/dumper/generic/sql.go
- pkg/dumper/query/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/reader.go
Group by condition was causing huge performance issue in our tests, so better to not expose this feature for the klepto users for now
> Remove group by field

- README.md
- cmd/steal.go
- examples/user-orders-using-matchers.toml
- features/mysql_test.go
- features/postgres_test.go
- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
- pkg/config/config.go
- pkg/dumper/dumper.go
- pkg/dumper/generic/sql.go
- pkg/dumper/query/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/reader.go
This PR introduces the new `Matchers` config, it will prevent users from having to repeat filters for every table
> Introduce matchers configuration 

- Gopkg.lock
- Gopkg.toml
- cmd/update.go
By switching to hellofresh/updater-go we get:
- The option to update to a specific version
- Cleaner messages when the version is already up to date
> Switch to hellofresh/updater-go

- .zappr.yaml
This PR adds a Zappr config to make `qa` and `pm` approvals optional
> PT-6669 Update Zappr config to not require qa and pm +1s

- .gitignore
- cmd/init.go
- cmd/root.go
- cmd/steal.go
- fixtures/.klepto.toml
- pkg/anonymiser/anonymiser.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/dumper/dumper.go
- pkg/dumper/engine/engine.go
- pkg/dumper/query/dumper.go
- pkg/reader/postgres/postgres.go
First piece extracted from bigger brother https://github.com/hellofresh/klepto/pull/110
In this PR:
- improved error reporting
- moved config loading to config package and covered it with basic tests
- fixed `init` command as generated toml file has invalid structure - go sruct embedding for some reasons works differently for writing toml and reading it
> PT-6909 Extracted spec loading to config and added some tests

- pkg/dumper/engine/engine.go
- pkg/dumper/query/dumper.go
- pkg/reader/reader.go
- pkg/reader/reader_test.go
One more piece extracted from https://github.com/hellofresh/klepto/pull/110
This time - reader options extracted from implementations private methods to a builder function.
> PT-6909 Extracted reader options to builder from private methods

- README.md
- cmd/init.go
- cmd/steal.go
- features/mysql_test.go
- features/postgres_test.go
- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/dumper/dumper.go
- pkg/dumper/engine/engine.go
- pkg/dumper/query/dumper.go
- pkg/reader/engine/engine.go
- pkg/reader/reader.go
The last piece extracted from https://github.com/hellofresh/klepto/pull/110
Instead of passing matcher aliases everywhere and checking them - they are checked and replaced on config load once.
Dependend on https://github.com/hellofresh/klepto/pull/112 and has to be rebased after merge.
> PT-6909 Apply matcher aliases to tables on config load 

- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
Currently invalid anonymiser is just ignored. With this fix it will be reported to the log as error and to the dump to make it broken and attract attention.
> PT-6909 Handle invalid anonymiser

- pkg/dumper/query/dumper.go
While engine dumper handles several tables dumping correctly query dumper was missing sync part so the first finished table was finishing the whole process.
> PT-6909 Fixed writing to the closed channel

- fixtures/pg_simple.sql
- pkg/reader/postgres/reader.go
I've just started using klepto to create a staging database, and run into the problem that the views are interfering with klepto.
there was a PR previously opened, but is now closed: https://github.com/hellofresh/klepto/pull/99
> ignore views/foreign tables/temporary tables in postgres databases

- cmd/steal.go
- pkg/dumper/dumper.go
- pkg/dumper/postgres/dumper.go
- pkg/dumper/postgres/postgres.go
- pkg/reader/postgres/pg_dump.go
On AWS RDS Postgres servers the "superuser" does not have permission to run the `ALTER TABLE %s DISABLE TRIGGER ALL` command. To get around this I've added a CLI argument `--to-rds` that indicates the dump is being done to an RDS database, and so will switch to looking up all the Foreign Keys in the database, and then using `ALTER TABLE %s DROP CONSTRAINT %s`/`ALTER TABLE %s ADD CONSTRAINT %s %s` to enable and disable the constraints.
> Support dumping to AWS RDS Postgres servers

- Dockerfile
Hello 👋!
Just found a problem with Dockerfile.
It was impossible to build an image.
So, glad to propose this fix.
Now command works as expected:
```shell
docker build --build-arg KLEPTO_VERSION=0.3.1 --tag klepto .
```
Thank you 🤝 !
> Fix docker build.

- cmd/init.go
- cmd/steal.go
- cmd/update.go
- go.mod
- go.sum
- pkg/anonymiser/anonymiser.go
- pkg/config/config.go
- pkg/dumper/dumper.go
- pkg/dumper/engine/engine.go
- pkg/dumper/mysql/dumper.go
- pkg/dumper/mysql/mysql.go
- pkg/dumper/postgres/dumper.go
- pkg/dumper/query/dumper.go
- pkg/reader/engine/engine.go
- pkg/reader/mysql/reader.go
- pkg/reader/postgres/reader.go
This PR replace the use of `github.com/pkg/errors` package with the native approach
> Remove github.com/pkg/errors

- go.mod
- go.sum
Related ticket: https://hellofresh.atlassian.net/browse/EES-7127
--- 
This PR updates the updater-go lib version to remove deprecation warning on timeouts
> Update updater-go version

- .goreleaser.yml
Adds a darwin-arm64 build configuration for Apple M1/M2 to the goreleaser config.
> Build darwin-arm64 for Apple Silicon

- cmd/steal.go
- features/mysql_test.go
- features/postgres_test.go
- pkg/dumper/dumper.go
- pkg/dumper/engine/engine.go
- pkg/dumper/query/dumper.go
This was prompted as a workaround for the issue presented in #139.
By allowing data-only transfers to be run, we can use multiple config files in order to extract multiple subsets from the same table. An initial run, without `--data-only`, copies the DB structure and anonmized users while a second run using `--data-only` and a different config file copies unmodified versions of admin users to the same table.
It's likely useful in many other cases as well.
I'm happy to add some testing for this if necessary, but I'd appreciate some pointers on where best to add it. There doesn't seem to be any existing tests for the Dumper Engine or the `steal` command, where the bulk of this takes place.
> Add --data-only to copy data without structure

- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
The Latitude and Longitude faker functions return a float32 value.
Prior to this fix, the anonymized value was set to the string `"<float32 Value>"` rather than to the string representing the Latiude or Longitude.
> Fix Latitude and Longitude anonymization

- features/mysql_test.go
- features/postgres_test.go
- fixtures/.klepto.toml
- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/dsn/dsn.go
- pkg/dumper/mysql/dumper.go
- pkg/dumper/mysql/mysql.go
- pkg/dumper/postgres/dumper.go
- pkg/dumper/query/dumper.go
- pkg/dumper/query/writer.go
- pkg/reader/mysql/mysql.go
- pkg/reader/mysql/reader.go
- pkg/reader/postgres/reader.go
This PR fix a typo in the sample config, removes some unused code, replace deprecated `ioutil` calls and other static checks
> Fix imports and cleanup code

- docker-compose.yml
The 'version' property in docker-compose.yml file is now officially considered obsolete.
This PR removes it.
> EPS-105 - remove version from docker-compose.yml
