hellofresh/klepto

- cmd/steal.go
- database/database.go
- database/mysql_anonymiser.go
- Add semicolon at the end of table data
- Detect type of data to help decide whether to wrap value in quotes
- Prepare for refactor of table scanner
> Fix output

- cmd/steal.go
- database/mysql/dumper.go
To improve readability of code.
> Clarify purpose of insert-statements-creation function

- .gitignore
- Gopkg.lock
- cmd/init.go
- cmd/root.go
- example.toml
- pkg/config/config.go
- Added `init cmd`
- Added configuration struct
> Add init cmd

- pkg/reader/postgres/pg_dump.go
- pkg/reader/postgres/postgres.go
- pkg/reader/postgres/reader.go
This PR adds pg_dump as a dependency so we can fetch the structure of a table.
> Add pg_dump in order to get the table schema

- Gopkg.lock
- Gopkg.toml
- cmd/steal.go
- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
- pkg/config/config.go
Making the anonymizer config aware
> Making the anonymizer config aware

- cmd/steal.go
- pkg/anonymiser/anonymiser.go
- pkg/dumper/dumper.go
- pkg/dumper/query/dumper.go
- pkg/dumper/text/dumper.go
- pkg/reader/generic/sql.go
- Makes the channels more reliable
- Added a done channel to control the application flow
> Better channels

- pkg/anonymiser/anonymiser_test.go
- pkg/dumper/dumper.go
- pkg/dumper/query/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/reader.go
Extracted from https://github.com/hellofresh/klepto/pull/46
> Allow for closing dumpers and readers mainly for testing purposes

- pkg/anonymiser/anonymiser_test.go
- pkg/reader/generic/sql.go
- pkg/reader/postgres/reader.go
- pkg/reader/reader.go
because it makes live sweeter for copyin
> Back to the column without table standard 

- .travis.yml
- cmd/steal.go
- docker-compose.yml
- features/postgres_test.go
- pkg/dumper/driver.go
- pkg/dumper/dumper.go
- pkg/dumper/postgres/dumper.go
- pkg/dumper/postgres/postgres.go
- pkg/reader/driver.go
This was created with some of the #46 PR code. It was easier to redo it in a new PR.
> Postgres dumper

- Gopkg.lock
- pkg/anonymiser/anonymiser.go
- pkg/dumper/query/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/reader.go
- Fixed relationship bug when fetching related data for one table
> Fix relationships

- pkg/dumper/postgres/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/mysql/reader.go
- pkg/reader/postgres/pg_dump.go
- pkg/reader/postgres/reader.go
- pkg/reader/reader.go
This PR introduces the idea of having a SqlEngine for the reader that can then be used by the SqlReader. 
This allows for a single place to do caching etc.
> Improve Sql reader

- cmd/init.go
- pkg/anonymiser/anonymiser.go
- pkg/config/config.go
- pkg/dumper/postgres/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/postgres/reader.go
- Improved log messages
- Improved log levels
- Fixed a bug when using the anonymization feature but with no limit
> Log improvements

- pkg/dumper/mysql/dumper.go
> Log with fields

- pkg/dumper/driver.go
- pkg/dumper/dumper.go
> Check missing type assertion

- pkg/dumper/mysql/dumper.go
- pkg/dumper/postgres/dumper.go
> Rollback when insert fail

- cmd/steal.go
- pkg/reader/driver.go
- pkg/reader/reader.go
> Close missing connections

- pkg/anonymiser/anonymiser.go
- pkg/anonymiser/anonymiser_test.go
- pkg/dumper/generic/sql.go
- pkg/dumper/mysql/dumper.go
- pkg/dumper/query/dumper.go
- pkg/reader/generic/sql.go
- pkg/reader/reader.go
Remove extra `configTables config.Tables` argument
> Remove extra config tables args

- README.md
> Change docs order

- README.md
Hi! This project is really cool - in the past I've used hacky shell scripts to copy data between environments but this is much nicer.
I've made a few tweaks to the README to make it easier to understand and more consistent, hope that's ok.
> Copyedit and tweak README for clarity

- cmd/steal.go
Concurrency value now defaults to the number of available cpu's
> Change concurrency default value

- .github/workflows/testing.yml
- .zappr.yaml
> Removed unused legacy zappr file
